export const APPWRITE_CONFIG = {
  ENDPOINT: import.meta.env.VITE_APPWRITE_ENDPOINT,
  PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_ID,
  // Buckets
  RECEIPTS_BUCKET_ID: import.meta.env.VITE_APPWRITE_RECEIPTS_BUCKET_ID,
  AVATARS_BUCKET_ID: import.meta.env.VITE_APPWRITE_AVATARS_BUCKET_ID,
  // Collections
  RECEIPTS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_RECEIPTS_COLLECTION_ID,
  USERS_INFO_COLLECTION_ID: import.meta.env.VITE_APPWRITE_USERS_INFO_COLLECTION_ID,
  ACCOUNTS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_ACCOUNTS_COLLECTION_ID,
  TRANSACTIONS_COLLECTION_ID: import.meta.env.VITE_APPWRITE_TRANSACTIONS_COLLECTION_ID,
};
