import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { Button } from "../components/ui/Button";
import { Input } from "../components/ui/Input";
import { Languages, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import toast from "react-hot-toast";
import { useTranslation } from "react-i18next";
import Logo from "../components/Logo";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const [showForgotModal, setShowForgotModal] = useState(false);
  const [forgotEmail, setForgotEmail] = useState("");
  const [forgotLoading, setForgotLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();
  const { t, i18n } = useTranslation();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    const result = await login(email, password);
    setLoading(false);

    if (result.success) {
      toast.success(t("auth.successLogin"));
      navigate("/");
    } else {
      toast.error(result.error || t("auth.errorLogin"));
    }
  };

  const handleForgotPassword = async (e) => {
    e.preventDefault();
    setForgotLoading(true);

    try {
      const emailServerUrl =
        import.meta.env.VITE_EMAIL_SERVER_URL || "http://localhost:3001";
      const resetLink = `${window.location.origin}/reset-password`; // This page needs to be created or handled
      const lang = i18n.language || "es";

      // Note: We are sending a generic link for now as we don't have the token generation logic fully exposed here.
      // Ideally, we should call an endpoint that generates the token and sends the email.
      // Since we are using a custom server, we'll just send the request.
      // However, for a real reset, we need a token.
      // Let's assume the user will just receive a notification for now, or we need to implement the token generation on the server.
      // Given the constraints, we will send the request to the server.

      await fetch(`${emailServerUrl}/send-password-reset`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: forgotEmail,
          resetLink, // In a real app, this should include a token generated by the backend
          lang,
        }),
      });

      toast.success(t("auth.recoveryEmailSent"));
      toast(t("auth.recoveryEmailSentDesc"), { duration: 5000 });
      setShowForgotModal(false);
      setForgotEmail("");
    } catch (error) {
      console.error("Error sending recovery email:", error);
      toast.error(t("common.error"));
    } finally {
      setForgotLoading(false);
    }
  };

  const toggleLanguage = () => {
    const newLang = i18n.language === "en" ? "es" : "en";
    i18n.changeLanguage(newLang);
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-zinc-950 p-4 relative">
      {/* Language Toggle - Top Right */}
      <motion.button
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        onClick={toggleLanguage}
        className="absolute top-4 right-4 p-2 rounded-full bg-zinc-900 text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors flex items-center gap-2"
      >
        <Languages size={20} />
        <span className="text-sm font-medium uppercase">
          {i18n.language === "en" ? "es" : "en"}
        </span>
      </motion.button>

      <AnimatePresence>
        {showForgotModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-md bg-zinc-900 border border-zinc-800 rounded-2xl p-6 shadow-xl relative"
            >
              <button
                onClick={() => setShowForgotModal(false)}
                className="absolute top-4 right-4 text-zinc-400 hover:text-white"
              >
                <X size={20} />
              </button>
              <h2 className="text-xl font-bold text-white mb-2">
                {t("auth.resetPassword")}
              </h2>
              <p className="text-zinc-400 mb-6">
                {t("auth.enterEmailRecovery")}
              </p>
              <form onSubmit={handleForgotPassword} className="space-y-4">
                <Input
                  label={t("auth.email")}
                  type="email"
                  placeholder="name@example.com"
                  value={forgotEmail}
                  onChange={(e) => setForgotEmail(e.target.value)}
                  required
                  autoFocus
                />
                <div className="flex justify-end gap-3">
                  <Button
                    type="button"
                    variant="ghost"
                    onClick={() => setShowForgotModal(false)}
                    className="text-zinc-400 hover:text-white"
                  >
                    {t("common.cancel")}
                  </Button>
                  <Button
                    type="submit"
                    className="bg-emerald-500 hover:bg-emerald-600 text-zinc-950 font-bold"
                    isLoading={forgotLoading}
                  >
                    {t("auth.sendRecoveryLink")}
                  </Button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md space-y-8"
      >
        <div className="text-center space-y-2">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: "spring", duration: 0.6, delay: 0.2 }}
            className="inline-flex items-center justify-center w-20 h-20 mb-4"
          >
            <Logo className="w-full h-full" />
          </motion.div>
          <h1 className="text-3xl font-bold tracking-tight text-white">
            {t("auth.welcomeBack")}
          </h1>
          <p className="text-zinc-400">{t("auth.enterCredentials")}</p>
        </div>

        <motion.form
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          onSubmit={handleSubmit}
          className="space-y-6 bg-zinc-900/50 p-8 rounded-3xl border border-zinc-800/50 backdrop-blur-xl"
        >
          <Input
            label={t("auth.email")}
            type="email"
            placeholder="name@example.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />

          <Input
            label={t("auth.password")}
            type="password"
            placeholder="••••••••"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />

          <div className="flex items-center justify-between">
            <div className="text-sm">
              <button
                type="button"
                onClick={() => setShowForgotModal(true)}
                className="font-medium text-emerald-500 hover:text-emerald-400"
              >
                {t("auth.forgotPassword")}
              </button>
            </div>
          </div>

          <Button
            type="submit"
            className="w-full bg-emerald-500 hover:bg-emerald-600 text-zinc-950 font-bold"
            isLoading={loading}
          >
            {t("auth.signIn")}
          </Button>

          <p className="text-center text-sm text-zinc-400">
            {t("auth.dontHaveAccount")}{" "}
            <Link
              to="/register"
              className="font-medium text-emerald-500 hover:text-emerald-400"
            >
              {t("auth.signUp")}
            </Link>
          </p>
        </motion.form>
      </motion.div>
    </div>
  );
}
